on:
  - push

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.6.1
        with:
          architecture: 'x64'
          distribution: 'full'
          version: '8.2'

      - name: Install Package and its Dependencies
        run: raco pkg install --auto --batch

      - name: Build Executable
        run: raco exe -o streamline ./cli.rkt

      - name: Upload Executable
        uses: actions/upload-artifact@v2
        with:
          name: linux-release
          path: ./streamline
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
