on:
  - push
jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Cache Racket dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/racket
            ~/.local/share/racket
          key: ${{ runner.os }}-racket-8.11

      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.6.1
        with:
          architecture: 'x64'
          distribution: 'full'
          version: '8.11'

      - name: Install raco-cross for cross compilation
        run: raco pkg install --skip-installed --auto raco-cross

      - name: Install Linux Package and its Dependencies
        run: raco cross --target x86_64-linux --skip-setup pkg install --skip-installed --auto --batch

      - name: Build Linux Executable
        run: raco cross --target x86_64-linux --skip-setup exe -o streamline-linux ./cli.rkt

      - name: Install M1 Packages and its Dependencies
        run: raco cross --target aarch64-macosx --skip-setup pkg install --skip-installed --auto --batch

      - name: Build M1 Executable
        run: raco cross --target aarch64-macosx exe -o streamline-arm-mac ./cli.rkt

      - name: Install x86 Max Executable
        run: raco cross --target x86_64-macosx --skip-setup pkg install --skip-installed --auto --batch

      - name: Build x86 Mac Executable
        run: raco cross --target x86_64-macosx exe -o streamline-x86-mac ./cli.rkt

      - name: Upload Linux Executable
        uses: actions/upload-artifact@v2
        with:
          name: streamline-linux
          path: ./streamline-linux

      - name: Upload M1 Executable
        uses: actions/upload-artifact@v2
        with:
          name: streamline-arm-mac
          path: ./streamline-arm-mac

      - name: Upload x86 Mac Executable
        uses: actions/upload-artifact@v2
        with:
          name: streamline-x86-mac
          path: ./streamline-x86-mac

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./streamline-linux
            ./streamline-arm-mac
            ./streamline-x86-mac
